server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/electricityconsumptionsystem?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:sqlmap/*.xml
  type-aliases-package: com.yangchenle.electricityconsumptionsystem.entity